# Generated by Django 3.2.20 on 2023-10-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cdrer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xyutit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvcbdh', models.BigIntegerField()),
                ('yruru', models.BigIntegerField()),
            ],
        ),
    ]
